Replace StandardCharsets (min SDK 19) with Charset.forName()
StandardCharsets has been added in Java 1.7 and Android SDK 19 and thus
cause a java.lang.NoClassDefFoundError in Android 18 and below.

Should resolve issue #129